# Generated by Django 4.2.4 on 2023-09-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='username',
            new_name='confirmpassword',
        ),
    ]
