# Generated by Django 4.2.4 on 2023-09-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0002_rename_username_customer_confirmpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profileimage',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
